### ISSUE TITLE
Reassigning/overwriting file variable breaks a loop that creates a long string

### ISSUE THREAD

**Issue by progamateur** [blade-lang/blade#90] opened 2021-10-31 20:11 UTC
OS: Windows 10 Professional version: 21H1
Blade version : 0.0.6

Run the following script,

    var str_len = 1500
    #str_len = 200
    var file_id = file('foo')
    file_id = file('bar')
    # Loop for creating 'str' string
    var str = ''
    iter var idx = 0; idx < str_len; idx++ {
        str += '1'
    }
    echo 'End of iter loop'

Result: the last line is not executed because the loop that creates the string stops before the end and interrupts the script.

If you either uncomment line 2 `# str_len = 200` (the string length is reduced to 200 characters) or comment line 4 `file_id = file('bar')` (file_id is no longer overwrited), `End of iter loop` is displayed as expected.

**Comment by mcfriend99** [comment] 2021-11-02 15:24
Which compiler is your build based on??

**Comment by progamateur** [comment] 2021-11-02 16:55
cmake version 3.21.2
Visual Studio 16 2019 :
 - SDK version 10.0.19041.0 to target Windows 10.0.19043.
 - MSVC 19.29.30136.0
 
What I've done for blade building :

C:\> git clone https://github.com/blade-lang/blade.git
Cloning into 'blade'...
remote: Enumerating objects: 9961, done.
remote: Counting objects: 100% (3144/3144), done.
remote: Compressing objects: 100% (2221/2221), done.
remote: Total 9961 (delta 1862), reused 1350 (delta 904), pack-reused 6817
Receiving objects: 100% (9961/9961), 17.33 MiB | 3.58 MiB/s, done.
Resolving deltas: 100% (5729/5729), done.


C:\>cd .\blade
C:\blade>cmake -B build
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.29.30136.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for getopt.h
-- Looking for getopt.h - not found
-- Looking for termios.h
-- Looking for termios.h - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for sys/time.h
-- Looking for sys/time.h - not found
-- Looking for sys/utsname.h
-- Looking for sys/utsname.h - not found
-- Looking for sys/errno.h
-- Looking for sys/errno.h - not found
-- Looking for dirent.h
-- Looking for dirent.h - not found
-- Looking for sqlite3.h
-- Looking for sqlite3.h - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - not found
-- Looking for asprintf
-- Looking for asprintf - not found
-- Looking for strsep
-- Looking for strsep - not found
-- Looking for gettimeofday
-- Looking for gettimeofday - not found
-- Looking for utime
-- Looking for utime - found
-- Looking for basename
-- Looking for basename - not found
-- Looking for dirname
-- Looking for dirname - not found
--
-- Blade configuration summary
--   Install prefix .................. : C:/Program Files (x86)/blade
--   C compiler ...................... : C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
--   Build type ...................... :
--   C compiler flags ................ :
--   IPO/LTO ......................... : enabled
--
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Configuring done
-- Generating done
-- Build files have been written to: C:/blade/build


C:\blade>cmake --build build
Microsoft (R) Build Engine version 16.11.1+3e40a09f8 pour .NET Framework
Copyright (C) Microsoft Corporation. Tous droits réservés.

  Checking Build System
  Building Custom Rule C:/blade/thirdparty/asprintf/CMakeLists.txt
  vasprintf-c99.c
  asprintf.c
  Génération de code en cours...
  asprintf.vcxproj -> C:\blade\build\thirdparty\asprintf\asprintf.dir\Debug\asprintf.lib
  Building Custom Rule C:/blade/thirdparty/gettimeofday/CMakeLists.txt
  gettimeofday.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: l'expansion de macro produisant 'defined' a un comportement indéfini [C:\blade\
build\thirdparty\gettimeofday\gettimeofday.vcxproj]
  gettimeofday.vcxproj -> C:\blade\build\thirdparty\gettimeofday\gettimeofday.dir\Debug\gettimeofday.lib
  Building Custom Rule C:/blade/thirdparty/json-parser/CMakeLists.txt
  json.c
C:\blade\thirdparty\json-parser\json.c(157,80): warning C4311: 'cast de type' : troncation de pointeur de 'json_object_entry *' à 'unsigned long' [C:\blade\build\thirdparty\jso
n-parser\json-parser.vcxproj]
  json-parser.vcxproj -> C:\blade\build\thirdparty\json-parser\json-parser.dir\Debug\json-parser.lib
  Building Custom Rule C:/blade/CMakeLists.txt
  pcre2_auto_possess.c
  pcre2_chartables.c
  pcre2_compile.c
  pcre2_config.c
  pcre2_context.c
  pcre2_convert.c
  pcre2_dfa_match.c
  pcre2_error.c
  pcre2_extuni.c
  pcre2_find_bracket.c
  pcre2_jit_compile.c
  pcre2_maketables.c
  pcre2_match.c
  pcre2_match_data.c
  pcre2_newline.c
  pcre2_ord2utf.c
  pcre2_pattern_info.c
  pcre2_script_run.c
  pcre2_serialize.c
  pcre2_string_utils.c
  Génération de code en cours...
  Compilation en cours...
  pcre2_study.c
  pcre2_substitute.c
  pcre2_substring.c
  pcre2_tables.c
  pcre2_ucd.c
  pcre2_valid_utf.c
  pcre2_xclass.c
  Génération de code en cours...
  libpcre.vcxproj -> C:\blade\build\libpcre.dir\Debug\libpcre.lib
  Building Custom Rule C:/blade/thirdparty/strsep/CMakeLists.txt
  strsep.c
  strsep.vcxproj -> C:\blade\build\thirdparty\strsep\strsep.dir\Debug\strsep.lib
  Building Custom Rule C:/blade/CMakeLists.txt
  Exporting libs, tests, and benchmark scripts...
  Building Custom Rule C:/blade/thirdparty/sqlite/CMakeLists.txt
  sqlite3.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: l'expansion de macro produisant 'defined' a un comportement indéfini [C:\blade\
build\thirdparty\sqlite\sqlite.vcxproj]
  sqlite.vcxproj -> C:\blade\build\bin\sqlite.lib
  Building Custom Rule C:/blade/CMakeLists.txt
  blade_dict.c
  blade_file.c
  blade_list.c
  blade_string.c
C:\blade\src\blade_string.c(653,68): warning C4090: 'fonction' : qualificateurs 'const' différents [C:\blade\build\libblade.vcxproj]
C:\blade\src\blade_string.c(760,68): warning C4090: 'fonction' : qualificateurs 'const' différents [C:\blade\build\libblade.vcxproj]
C:\blade\src\blade_string.c(871,70): warning C4090: 'fonction' : qualificateurs 'const' différents [C:\blade\build\libblade.vcxproj]
  blade_range.c
  blob.c
  bytes.c
  compiler.c
  debug.c
  memory.c
  module.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: l'expansion de macro produisant 'defined' a un comportement indéfini [C:\blade\
build\libblade.vcxproj]
C:\blade\src\module.c(197,21): warning C4090: 'return' : qualificateurs 'const' différents [C:\blade\build\libblade.vcxproj]
C:\blade\src\module.c(202,21): warning C4090: 'return' : qualificateurs 'const' différents [C:\blade\build\libblade.vcxproj]
  native.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: l'expansion de macro produisant 'defined' a un comportement indéfini [C:\blade\
build\libblade.vcxproj]
  object.c
  pathinfo.c
  scanner.c
  table.c
  util.c
  value.c
  vm.c
  base64.c
  Compilation en cours...
  date.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: l'expansion de macro produisant 'defined' a un comportement indéfini [C:\blade\
build\libblade.vcxproj]
  io.c
  math.c
  os.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: l'expansion de macro produisant 'defined' a un comportement indéfini [C:\blade\
build\libblade.vcxproj]
  socket.c
  hash.c
  json.c
  sqlite.c
  blade_getopt.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: l'expansion de macro produisant 'defined' a un comportement indéfini [C:\blade\
build\libblade.vcxproj]
  libblade.vcxproj -> C:\blade\build\bin\blade.lib
  Building Custom Rule C:/blade/CMakeLists.txt
  blade.c
  blade.lib(util.obj) : .netmodule ou module MSIL compilé avec /GL trouvé ; redémarrage de l'édition de liens avec /LTCG ; ajoutez /LTCG à la ligne de commande de l'édition de
  liens pour améliorer les performances de l'Éditeur de liens
LINK : warning LNK4075: ' /INCREMENTAL' ignoré à cause de la spécification '/LTCG' [C:\blade\build\blade.vcxproj]
  Génération de code en cours
C:\blade\src\blade_string.c(196): warning C4700: variable locale 'has_alpha' non initialisée utilisée [C:\blade\build\blade.vcxproj]
C:\blade\src\blade_string.c(180): warning C4700: variable locale 'has_alpha' non initialisée utilisée [C:\blade\build\blade.vcxproj]
  Fin de la génération du code
  blade.vcxproj -> C:\blade\build\bin\blade.exe
  Generating Blade header and folders...
  Compilation successful!
  Building Custom Rule C:/blade/CMakeLists.txt

**Comment by progamateur** [comment] 2021-11-02 22:30
Now I've installed blade using MSYS2 and MinGW and the script works fine. So something is wrong with Visual Studio.

**Comment by progamateur** [comment] 2021-11-03 16:02
Even with the new blade build (MSYS2/MINGW), an infinite loop that creates a long string and sends a system command, stops after a certain number of iterations.
If line 3 is uncommented (str_len = 50) or line 5 is commented (os.exec("cmd /c echo foo"), everything seems to be fine.
In MHO, the problem seems to be related to the management of inputs/outputs as in the previous problem.

    import os 
    var str_len = 500
    # str_len = 50
    while true {
        print('$')
        os.exec("cmd /c echo foo")
        var str_r = ''
        iter var idx = 0; idx < str_len; idx++ {
        str_r = str_r + idx + '\n'
        }
    }

**Comment by mcfriend99** [comment] 2021-11-03 16:26
I haven't gotten around to testing it on a Windows, but I am unable to replicate the issue on OSX or Linux. Looks like a GC issue. I'll test on Windows shortly and provide a fix for this issue.

**Comment by progamateur** [comment] 2021-11-03 16:33
OK, I'll wait to continue my evaluation... Good luck.

**Comment by mcfriend99** [comment] 2021-11-12 22:11
Fixed at 71f2e19bb07377a3f3399635397be4a2e71e41f9. 

@progamateur, please pull the latest changes and build again to test and let me know if the issue is fixed.

**Comment by progamateur** [comment] 2021-11-16 21:44
I just compiled the latest version of blade under MSVC, the problem seems to be solved for the two scripts that were causing problems.
Now I can continue my evaluation...

**Closed** 2021-11-16 23:14 UTC
Labels: bug, good first issue
